Add german translation
MaxKorlaar/hypixel-signatures pull request #49
Opened 2020-10-13 15:26 UTC by ghizzo01

Closes #31

2020-10-14 09:19 UTC, MaxKorlaar commented
Vielen Dank! I'll check it out on my computer soon 😄

2020-10-24 11:50 UTC, MaxKorlaar reviewed
I have reason to believe that these translations were done using Google Translate, causing them to be poorly translated and for loss of valid HTML. I am sorry, but I do not find this PR to be fit for approval at this time.

2020-10-24 15:06 UTC, ghizzo01 commented
Yes I used Google Translate to help myself with some words I wasn't sure about, but I do know German as my second language and I tried to make every translation as best as possible. However I'm still studying it, and I hope as part of the spirit of Hacktoberfest you will be able to point me in the right direction, hoping I haven't made too many mistakes.

I fixed some formatting mistakes I made along the way. I hope this gets me nearer to a valid submission

2020-10-25 13:35 UTC, MaxKorlaar requested changes
I appreciate your honesty. I've added some feedback to point you into the right direction.

2020-10-25 13:35 UTC, MaxKorlaar commented on resources/lang/de/validation.php
> +        'active_url'           => 'Das :attribute ist keine gültige URL. '
```suggestion
        'active_url'           => 'Das :attribute ist keine gültige URL. ',
```

2020-10-25 13:35 UTC, MaxKorlaar commented on resources/lang/de/home.php
> +            "Der <i> dynamische </ i> Teil bedeutet, dass sich diese Signaturen automatisch aktualisieren. Dies bedeutet, dass Sie Ihre Signatur nur einmal auswählen und verwenden müssen und wir auto
```suggestion
            "Der <i>dynamische</i> Teil bedeutet, dass sich diese Signaturen automatisch aktualisieren. Dies bedeutet, dass Sie Ihre Signatur nur einmal auswählen und verwenden müssen und wir automatisch sicherstellen, dass ihr Inhalt auf dem neuesten Stand ist.",
```

2020-10-25 13:35 UTC, MaxKorlaar commented on resources/lang/de/home.php
> +        'title'               => 'Hypixel Sygnatur & Instrumente',
```suggestion
        'title'               => 'Hypixel Sygnatur & Hilfsmittel',
```

I think this would be a better translation, do you agree?

2020-10-25 13:35 UTC, MaxKorlaar commented on resources/lang/de/home.php
> +            "Ich bin immer offen für Vorschläge! Etwas vermissen? Fühlen Sie sich frei, <a href='https://twitter.com/MaxKorlaar'>mich auf Twitter zu kontaktieren</a> und Vorschläge in unserem unten v
"oder und überprüfe"

This does not seem grammatically correct to me.

2020-10-25 13:35 UTC, MaxKorlaar commented on resources/lang/de/nav.php
> +        'beta_warning' => '<b>Heads up!</b> Hypixel.Paniek.de befindet sich noch in der Beta-Phase und kann gelegentlich unterbrochen werden. Wenn Sie Feedback haben oder möchten mehr Funktionalität
This sentence is not fully translated

2020-10-26 22:18 UTC, tintinmaster requested changes
There are many lines wrong or not how a german would say it. I don't want to do it via this code review feature, so maybe yo could accept this PR and I will improve the translation based on the merged PR?

2020-10-26 22:18 UTC, tintinmaster commented on resources/lang/de/footer.php
> +        'acknowledgements' => 'Bestätigungen'
```suggestion
        'acknowledgements' => 'Danksagungen'
```
This is a more suitable translation

2020-10-27 08:59 UTC, MaxKorlaar commented
> There are many lines wrong or not how a german would say it. I don't want to do it via this code review feature, so maybe yo could accept this PR and I will improve the translation based on the merged PR?

Thanks for your offer @tintinmaster! As it currently stands, I do not wish to merge this PR into the master branch, as that branch is the live and deployed version of the website. If you would like to create your own PR based on this work, then I recommend you to create a fork of the branch that is currently being proposed to merge and then create a PR from your fork to this repository 😄

2020-10-27 09:44 UTC, tintinmaster commented
@MaxKorlaar I totally forgot about this option :sweat_smile:. Will do this :)

2020-10-28 10:33 UTC, merged